// Generated by gencpp from file vanjee_msgs/VanjeeScan.msg
// DO NOT EDIT!


#ifndef VANJEE_MSGS_MESSAGE_VANJEESCAN_H
#define VANJEE_MSGS_MESSAGE_VANJEESCAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vanjee_msgs/VanjeePacket.h>

namespace vanjee_msgs
{
template <class ContainerAllocator>
struct VanjeeScan_
{
  typedef VanjeeScan_<ContainerAllocator> Type;

  VanjeeScan_()
    : header()
    , packets()  {
    }
  VanjeeScan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , packets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vanjee_msgs::VanjeePacket_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vanjee_msgs::VanjeePacket_<ContainerAllocator> >> _packets_type;
  _packets_type packets;





  typedef boost::shared_ptr< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> const> ConstPtr;

}; // struct VanjeeScan_

typedef ::vanjee_msgs::VanjeeScan_<std::allocator<void> > VanjeeScan;

typedef boost::shared_ptr< ::vanjee_msgs::VanjeeScan > VanjeeScanPtr;
typedef boost::shared_ptr< ::vanjee_msgs::VanjeeScan const> VanjeeScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vanjee_msgs::VanjeeScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vanjee_msgs::VanjeeScan_<ContainerAllocator1> & lhs, const ::vanjee_msgs::VanjeeScan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.packets == rhs.packets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vanjee_msgs::VanjeeScan_<ContainerAllocator1> & lhs, const ::vanjee_msgs::VanjeeScan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vanjee_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5f0488edc8e957eb50bd2379285a930";
  }

  static const char* value(const ::vanjee_msgs::VanjeeScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5f0488edc8e957eULL;
  static const uint64_t static_value2 = 0xb50bd2379285a930ULL;
};

template<class ContainerAllocator>
struct DataType< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vanjee_msgs/VanjeeScan";
  }

  static const char* value(const ::vanjee_msgs::VanjeeScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# vanjee LIDAR scan packets.\n"
"\n"
"Header           header         # standard ROS message header\n"
"VanjeePacket[] packets        # vector of raw packets\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vanjee_msgs/VanjeePacket\n"
"# Raw vanjee LIDAR packet.\n"
"\n"
"time stamp              # packet timestamp\n"
"uint8[1600] data        # packet contents\n"
"\n"
;
  }

  static const char* value(const ::vanjee_msgs::VanjeeScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.packets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VanjeeScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vanjee_msgs::VanjeeScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vanjee_msgs::VanjeeScan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "packets[]" << std::endl;
    for (size_t i = 0; i < v.packets.size(); ++i)
    {
      s << indent << "  packets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vanjee_msgs::VanjeePacket_<ContainerAllocator> >::stream(s, indent + "    ", v.packets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VANJEE_MSGS_MESSAGE_VANJEESCAN_H
